### ISSUE TITLE
wtx bench does not validate utf8 text

### ISSUE THREAD

**Issue by littledivy** [c410-f3r/regular-crates#25]
Hi, Author of fastwebsockets here. I was reading your blog post on wtx, nice work!

I noticed that the wtx bench does not validate if the text is valid UTF8 while fastwebsockets and tungstenite do that - which is a pretty big overhead for large text payloads.

Ref https://github.com/c410-f3r/regular-crates/blob/main/wtx/examples/common/mod.rs#L66
https://github.com/c410-f3r/regular-crates/blob/main/wtx/src/web_socket.rs#L136

**Comment by c410-f3r** [comment]
Hello @littledivy, nice to meet you!

Text payloads have their UTF-8 contents verified when read from a stream. Let's enumerate all possible situations:

* Unique `FIN` frame (No decompression): Whole payload is verified at https://github.com/c410-f3r/wtx/blob/c46ef8a0c01e52706ebdd8e729b8dab98564b7c7/wtx/src/web_socket.rs#L948-L950
* Continuation frames (No decompression): UTF-8 continuation is verified with a in-house `utf8`-crate-like algorithm (https://github.com/c410-f3r/wtx/blob/main/wtx/src/misc/incomplete_utf8_char.rs). First frame is verified at https://github.com/c410-f3r/wtx/blob/c46ef8a0c01e52706ebdd8e729b8dab98564b7c7/wtx/src/web_socket.rs#L208 and the remaining frames are verified at https://github.com/c410-f3r/wtx/blob/c46ef8a0c01e52706ebdd8e729b8dab98564b7c7/wtx/src/web_socket.rs#L770-L799
* Unique `FIN` frame (With decompression): Whole payload is verified at https://github.com/c410-f3r/wtx/blob/c46ef8a0c01e52706ebdd8e729b8dab98564b7c7/wtx/src/web_socket.rs#L948-L950
* Continuation frames (With decompression): For some reason, it is not possible to decompress and verify fragmented texts so each fragment is concatenated and the whole payload is verified at https://github.com/c410-f3r/wtx/blob/c46ef8a0c01e52706ebdd8e729b8dab98564b7c7/wtx/src/web_socket.rs#L195
* Control frames: They aren't supposed to be compressed and the raw bytes are verified at https://github.com/c410-f3r/wtx/blob/c46ef8a0c01e52706ebdd8e729b8dab98564b7c7/wtx/src/web_socket.rs#L716

Autobahn tests are available at https://c410-f3r.github.io/wtx/ and benchmarks at https://github.com/c410-f3r/wtx/blob/main/wtx-bench/src/main.rs. Let me know if there are more questions and I will happily answer them.

**Comment by littledivy** [comment]
Ah, I was looking at the wrong repository (`regular-crates/wtx` instead of `wtx`), my bad. Thank you!
